#!/usr/bin/env python3
"""Regenerate CueTap/Compile/Rules/VSCodeBuiltInRules.swift from an installed VS Code.

Every built-in extension's package.json lists the languages it contributes and the
language-configuration.json each one uses. The generated file carries those files byte for
byte, keyed by their path under the application's extensions folder, plus the language id
to file map, so `cuetap compile` can resolve vscode-<language id> on a machine without
VS Code. Run it after updating VS Code and commit the result together with the fixtures
under tests/ that mirror the same files.

Usage: scripts/extract-vscode-rules.py [path to Visual Studio Code.app]
"""
import json
import os
import re
import sys

APP = sys.argv[1] if len(sys.argv) > 1 else "/Applications/Visual Studio Code.app"
RESOURCES = os.path.join(APP, "Contents", "Resources", "app")
EXTENSIONS = os.path.join(RESOURCES, "extensions")
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT = os.path.join(ROOT, "CueTap", "Compile", "Rules", "VSCodeBuiltInRules.swift")


def strip_comments(text):
    """package.json files ship as plain JSON; this only guards against a stray comment."""
    return re.sub(r"^\s*//.*$", "", text, flags=re.MULTILINE)


def main():
    if not os.path.isdir(EXTENSIONS):
        sys.exit(f"No extensions folder at {EXTENSIONS}")
    with open(os.path.join(RESOURCES, "package.json"), encoding="utf-8") as handle:
        version = json.load(handle)["version"]
    languages = {}
    extensions = {}
    files = {}
    for folder in sorted(os.listdir(EXTENSIONS)):
        manifest = os.path.join(EXTENSIONS, folder, "package.json")
        if not os.path.isfile(manifest):
            continue
        with open(manifest, encoding="utf-8") as handle:
            contributes = json.loads(strip_comments(handle.read())).get("contributes", {})
        for language in contributes.get("languages", []):
            configuration = language.get("configuration")
            identifier = language.get("id")
            if not configuration or not identifier:
                continue
            path = os.path.normpath(os.path.join(EXTENSIONS, folder, configuration))
            if not os.path.isfile(path):
                continue
            key = os.path.relpath(path, EXTENSIONS)
            with open(path, encoding="utf-8") as handle:
                text = handle.read()
            if '"""##' in text or "\\##" in text:
                sys.exit(f"{key} cannot be embedded in a ##\"\"\" raw string")
            files[key] = text
            languages.setdefault(identifier, key)
            for extension in language.get("extensions", []):
                extensions.setdefault(identifier, [])
                if extension not in extensions[identifier]:
                    extensions[identifier].append(extension)
    lines = [
        "// Generated by scripts/extract-vscode-rules.py from Visual Studio Code %s. Do not edit by hand." % version,
        "// The files are Microsoft's language-configuration.json files from the MIT-licensed VS Code",
        "// source, embedded unchanged; see THIRD-PARTY-NOTICES.md.",
        "",
        "enum VSCodeBuiltInRules {",
        '    static let version = "%s"' % version,
        "",
        "    /// Language id to the path of its configuration file under the extensions folder.",
        "    static let languages: [String: String] = [",
    ]
    for identifier in sorted(languages):
        lines.append('        "%s": "%s",' % (identifier, languages[identifier]))
    lines += ["    ]", "", "    /// File extensions each language claims, as its extension declares them.", "    static let extensions: [String: [String]] = ["]
    for identifier in sorted(extensions):
        lines.append('        "%s": [%s],' % (identifier, ", ".join('"%s"' % e for e in extensions[identifier])))
    lines += ["    ]", "", "    /// Configuration files by path, byte for byte as VS Code ships them.", "    static let files: [String: String] = ["]
    for key in sorted(files):
        lines.append('        "%s": %s,' % (key, "%s_%s" % ("file", re.sub(r"[^A-Za-z0-9]", "_", key))))
    lines += ["    ]", ""]
    for key in sorted(files):
        name = "file_" + re.sub(r"[^A-Za-z0-9]", "_", key)
        lines.append("    /// %s" % key)
        lines.append('    static let %s = ##"""' % name)
        # Content lines carry the closing delimiter's indentation, which Swift strips again.
        lines += [("    " + line) if line else "" for line in files[key].rstrip("\n").split("\n")]
        lines.append('    """##')
        lines.append("")
    with open(OUTPUT, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines).rstrip("\n") + "\n}\n")
    print("wrote %s: VS Code %s, %d languages, %d files" % (OUTPUT, version, len(languages), len(files)))


if __name__ == "__main__":
    main()
